stages:
  - build
  - package

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

build_java:
  image: eclipse-temurin:21-jdk-alpine
  stage: build
  cache:
    key:
      files:
        - build.gradle
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - .gradle/wrapper
      - .gradle/caches
    policy: pull-push
  script:
    - ./gradlew libertyPackage
  artifacts:
    paths:
      - build/wlp/usr/shared/resources/*.jar
      - build/libs/*.war

build_image:
  image: docker:24.0.5-cli
  services:
    - name: docker:24.0.5-dind
      variables:
        HEALTHCHECK_TCP_PORT: "2375"
  stage: package
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache ca-certificates openssl
    - echo "$CI_REGISTRY_CA" | base64 -d > /usr/local/share/ca-certificates/internal-ca.crt
    - update-ca-certificates
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_IID
