stages:
  - build
  - package

variables:
  IMAGE_NAME: web4_jakartaee
  FULL_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${IMAGE_NAME}

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build_java:
  stage: build
  image: eclipse-temurin:21-jdk-alpine
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

build_image:
  stage: package
  image: docker:24.0.9-cli
  services:
    - docker:24.0.9-dind
  needs:
    - build_java
  tags:
    - docker
  script:
    - docker build -t $FULL_IMAGE .
    - docker push $FULL_IMAGE

